name: Node.js CI and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Check for lock file
      run: |
        if [ -f package-lock.json ]; then
          echo "Found package-lock.json, caching dependencies"
        else
          echo "No lock file found, using regular install"
        fi
    
    - name: Check package.json scripts
      run: npm run || echo "No npm scripts defined"
    
    # 构建 TypeScript 项目（如果有 tsconfig.json）
    - name: Check for TypeScript
      run: |
        if [ -f tsconfig.json ]; then
          echo "TypeScript project detected"
          npx tsc --version || npm install typescript --no-save
        else
          echo "No TypeScript config found"
        fi
    
    # 尝试构建，如果有 tsconfig.json 则使用 tsc
    - name: Build
      run: |
        if [ -f tsconfig.json ]; then
          npx tsc || npm run build --if-present
        else
          npm run build --if-present
        fi
    
    # 如果有 test 脚本则运行测试
    - name: Test (if exists)
      run: |
        if [ -f package.json ] && grep -q '"test"' package.json; then
          npm test
        else
          echo "No test script found, skipping tests"
        fi